version: '3'

services:
  db:
    image: mysql:8.0
    container_name: docker-mysql
    ports:
      - 3306:3306
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
    restart: always
    networks:
      - backend
  backend:
    image:
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: 'on-failure'
    networks:
      - wanted_networks
networks:
  backend:
    driver: bridge
