version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - 3307:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
    env_file: .env
    environment:
      - MYSQL_ROOT_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - TZ: Asia/Seoul
    networks:
      - backend
    restart: always
  backend:
    image:
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: 'on-failure'
    networks:
      - wanted_networks
networks:
  backend:
    driver: bridge
